/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import javax.swing.JOptionPane;

/**
 *
 * @author HAMAZ KHAN
 */
public class addResult extends javax.swing.JFrame {

    /**
     * Creates new form page4
     */
    public addResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Rid = new javax.swing.JFormattedTextField();
        subject1 = new javax.swing.JFormattedTextField();
        subject2 = new javax.swing.JFormattedTextField();
        subject3 = new javax.swing.JFormattedTextField();
        subject4 = new javax.swing.JFormattedTextField();
        subject5 = new javax.swing.JFormattedTextField();
        Rname = new javax.swing.JFormattedTextField();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        ClassBox = new javax.swing.JComboBox<>();
        label9 = new javax.swing.JLabel();
        RFname = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addStudent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1550, 900));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setPreferredSize(new java.awt.Dimension(1550, 900));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(44, 165, 182));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 30, 140, 50));

        Rid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Rid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RidActionPerformed(evt);
            }
        });
        jPanel2.add(Rid, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 700, 40));

        subject1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject1ActionPerformed(evt);
            }
        });
        jPanel2.add(subject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 700, 40));

        subject2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subject2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject2ActionPerformed(evt);
            }
        });
        jPanel2.add(subject2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 700, 40));

        subject3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subject3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject3ActionPerformed(evt);
            }
        });
        jPanel2.add(subject3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 700, 40));

        subject4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subject4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject4ActionPerformed(evt);
            }
        });
        jPanel2.add(subject4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 700, 40));

        subject5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subject5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject5ActionPerformed(evt);
            }
        });
        jPanel2.add(subject5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 700, 40));

        Rname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Rname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RnameActionPerformed(evt);
            }
        });
        jPanel2.add(Rname, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 700, 40));

        label1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label1.setText("Subject 05");
        jPanel2.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 120, 32));

        label2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label2.setText("Subject 04");
        jPanel2.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 120, 32));

        label3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label3.setText("Subject 03");
        jPanel2.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 120, 32));

        label4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label4.setText("Subject 02");
        jPanel2.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 120, 32));

        label5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label5.setText("Subject 01");
        jPanel2.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 120, 32));

        label6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label6.setText("Class");
        jPanel2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 120, 32));

        label7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label7.setText("ID");
        jPanel2.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 120, 32));

        label8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label8.setText("Name");
        jPanel2.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 120, 32));

        add.setBackground(java.awt.Color.black);
        add.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        add.setForeground(java.awt.Color.white);
        add.setText("Upload");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 610, 170, 50));

        ClassBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ClassBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matric", "9th", "8th", "7th", "6th", "5th", "4th", "3rd", "2nd", "1st", "kg2", "kg1", "kg", " " }));
        ClassBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassBoxActionPerformed(evt);
            }
        });
        jPanel2.add(ClassBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 700, 40));

        label9.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label9.setText("F/Name");
        jPanel2.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 120, 32));

        RFname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFnameActionPerformed(evt);
            }
        });
        jPanel2.add(RFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 700, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1550, 790));

        jPanel3.setBackground(new java.awt.Color(0, 182, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1070, 100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("_____________________________________________________");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 520, -1));

        addStudent.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        addStudent.setText("  Add result");
        jPanel3.add(addStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 440, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 150));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         dashBoard db = new dashBoard();
        db.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RidActionPerformed

    private void subject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject1ActionPerformed

    private void subject2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject2ActionPerformed

    private void subject3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject3ActionPerformed

    private void subject4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject4ActionPerformed

    private void subject5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject5ActionPerformed

    private void RnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RnameActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String getClass= ClassBox.getSelectedItem().toString();  // String getClass stored Class
        try {
        Sacred s = new Sacred();
        s.resultInsert(Rid.getText(), Rname.getText(), RFname.getText(), getClass, subject1.getText(), subject2.getText(), subject3.getText(), subject4.getText(), subject5.getText());
        JOptionPane.showMessageDialog(this, "Data Inserted Successfully");
        Rid.setText("");
        Rname.setText("");
        RFname.setText("");
        subject1.setText("");
        subject2.setText("");
        subject3.setText("");
        subject4.setText("");
        subject5.setText("");
        } catch (Exception e) {
              System.out.println("Error in ResultInsert Botton"+e);    
    }//GEN-LAST:event_addActionPerformed
    }
    
    private void ClassBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassBoxActionPerformed

    private void RFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RFnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ClassBox;
    private javax.swing.JFormattedTextField RFname;
    private javax.swing.JFormattedTextField Rid;
    private javax.swing.JFormattedTextField Rname;
    private javax.swing.JButton add;
    private javax.swing.JLabel addStudent;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JFormattedTextField subject1;
    private javax.swing.JFormattedTextField subject2;
    private javax.swing.JFormattedTextField subject3;
    private javax.swing.JFormattedTextField subject4;
    private javax.swing.JFormattedTextField subject5;
    // End of variables declaration//GEN-END:variables
}
