/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author HAMAZ KHAN
 */
public class addReport extends javax.swing.JFrame {

    /**
     * Creates new form page3
     */
    public addReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        name = new javax.swing.JFormattedTextField();
        Fname = new javax.swing.JFormattedTextField();
        id = new javax.swing.JFormattedTextField();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        Btn_Submit = new javax.swing.JButton();
        label7 = new javax.swing.JLabel();
        ClassBox = new javax.swing.JComboBox<>();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        DateBox = new com.toedter.calendar.JDateChooser();
        fee = new javax.swing.JTextField();
        label8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addStudent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1550, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(44, 165, 182));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 40, 110, 40));

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 700, 40));

        Fname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameActionPerformed(evt);
            }
        });
        jPanel2.add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 700, 40));

        id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 700, 40));

        label1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label1.setText("Name");
        jPanel2.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 150, 32));

        label2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label2.setText("F/Name");
        jPanel2.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 120, 32));

        label3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label3.setText("Class");
        jPanel2.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 120, 32));

        label5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label5.setText("Gender");
        jPanel2.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 120, 32));

        label6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label6.setText("ID");
        jPanel2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 120, 32));

        Btn_Submit.setBackground(java.awt.Color.black);
        Btn_Submit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Btn_Submit.setForeground(java.awt.Color.white);
        Btn_Submit.setText("Submit");
        Btn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SubmitActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 570, 220, 50));

        label7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label7.setText("Fee");
        jPanel2.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 120, 32));

        ClassBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ClassBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matric", "9th", "8th", "7th", "6th", "5th", "4th", "3rd", "2nd", "1st", "kg2", "kg1", "kg", " " }));
        jPanel2.add(ClassBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 700, 40));

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel2.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 150, 40));

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel2.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 150, 40));

        DateBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(DateBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 710, 40));

        fee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 710, 40));

        label8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label8.setText("Date");
        jPanel2.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 120, 32));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1620, 710));

        jPanel3.setBackground(new java.awt.Color(0, 182, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1070, 100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("____________________________________________________________________");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 680, -1));

        addStudent.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        addStudent.setText("  Add fee Report");
        jPanel3.add(addStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 500, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 150));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dashBoard db = new dashBoard();
        db.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void Btn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SubmitActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat();   // object is created for date jar 
        String daate = sdf.format(DateBox.getDate());       // daate stores date 
        String getClass= ClassBox.getSelectedItem().toString();  // String getClass stored Class
        // below 10 line is for to store gender in the gender variable
        String gender = "";
        if (male.isSelected()) {
            gender = "Male";
        }
        else if(female.isSelected()){
          gender = "Female";
        }
        else {
            gender = "";
        }
        try {
        Sacred s = new Sacred();
        s.insertFee(id.getText(), name.getText(), Fname.getText(), getClass, gender, daate, fee.getText());
        JOptionPane.showMessageDialog(this, "Data Inserted Successfully");
        id.setText("");
        name.setText("");
        Fname.setText("");
        fee.setText("");
        } catch (Exception e) {
                   System.out.println("Error in InsertFee Botton"+e);

        }
    }//GEN-LAST:event_Btn_SubmitActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Submit;
    private javax.swing.JComboBox<String> ClassBox;
    private com.toedter.calendar.JDateChooser DateBox;
    private javax.swing.JFormattedTextField Fname;
    private javax.swing.JLabel addStudent;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fee;
    private javax.swing.JRadioButton female;
    private javax.swing.JFormattedTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JRadioButton male;
    private javax.swing.JFormattedTextField name;
    // End of variables declaration//GEN-END:variables
}
