/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Haris Khan
 */
public class resultSearch extends javax.swing.JFrame {

    /**
     * Creates new form teacherSearch
     */
    public resultSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Rname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        Delet = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        RFname = new javax.swing.JTextField();
        Rid = new javax.swing.JTextField();
        Subject1 = new javax.swing.JTextField();
        Subject2 = new javax.swing.JTextField();
        Subject3 = new javax.swing.JTextField();
        Subject4 = new javax.swing.JTextField();
        Subject5 = new javax.swing.JTextField();
        ClassBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Select = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1550, 900));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.orange);
        jLabel2.setText("Result Modifiction");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 415, 43));

        jLabel3.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 130, 43));

        jLabel4.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("F/Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 130, 30));

        jLabel5.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Class");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 130, 30));

        jLabel6.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Subject 1");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 130, 30));

        jLabel7.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Subject 2");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 130, 30));

        jLabel8.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Subject 3");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 130, -1));

        jLabel17.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Subject 4");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, 130, 20));

        Rname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RnameActionPerformed(evt);
            }
        });
        jPanel1.add(Rname, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, 320, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("__________________________________________________________________________________________________");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 920, -1));

        Update.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 720, 150, 50));

        Delet.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Delet.setText("Delet");
        Delet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletActionPerformed(evt);
            }
        });
        jPanel1.add(Delet, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 720, 150, 50));

        Back.setBackground(java.awt.Color.cyan);
        Back.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 720, 150, 50));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("______________________________________________________________________________________________________");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 660, 1040, 30));

        jLabel16.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Subject 5");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 600, 130, 30));

        RFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFnameActionPerformed(evt);
            }
        });
        jPanel1.add(RFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 300, 320, 30));

        Rid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RidActionPerformed(evt);
            }
        });
        jPanel1.add(Rid, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, 320, 30));

        Subject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subject1ActionPerformed(evt);
            }
        });
        jPanel1.add(Subject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 320, 30));

        Subject2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subject2ActionPerformed(evt);
            }
        });
        jPanel1.add(Subject2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, 320, 30));

        Subject3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subject3ActionPerformed(evt);
            }
        });
        jPanel1.add(Subject3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 320, 30));

        Subject4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subject4ActionPerformed(evt);
            }
        });
        jPanel1.add(Subject4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, 320, 30));

        Subject5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subject5ActionPerformed(evt);
            }
        });
        jPanel1.add(Subject5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 600, 320, 30));

        ClassBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassBoxActionPerformed(evt);
            }
        });
        jPanel1.add(ClassBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, 320, 30));

        jLabel9.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 130, 30));

        Select.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Select.setText("Select");
        Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectActionPerformed(evt);
            }
        });
        jPanel1.add(Select, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 197, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletActionPerformed
        // TODO add your handling code here:
        Sacred s = new Sacred();
        int opt = JOptionPane.showConfirmDialog(null, "Are You Sure To Delet", "Delet", JOptionPane.YES_NO_OPTION);
        if(opt == 0){
        try {
            s.resultDelet((Rid.getText()));
            Rid.setText("");
            Rname.setText("");
            RFname.setText("");
            ClassBox.setText("");
            Subject1.setText("");
            Subject2.setText("");
            Subject3.setText("");
            Subject4.setText("");
            Subject5.setText("");

            JOptionPane.showMessageDialog(this, "Data Deleted Successfully");
        } catch (Exception e) {
            System.out.println("Error in DeletResult botton"+e);
        }
        }
    }//GEN-LAST:event_DeletActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        Sacred s = new Sacred();
        
        try {
            s.resultUpdate(Rid.getText(),Rname.getText(), RFname.getText(), ClassBox.getText(), Subject1.getText(), Subject2.getText(), Subject3.getText(), Subject4.getText(), Subject5.getText());
            Rid.setText("");
            Rname.setText("");
            RFname.setText("");
            ClassBox.setText("");
            Subject1.setText("");
            Subject2.setText("");
            Subject3.setText("");
            Subject4.setText("");
            Subject5.setText("");
            JOptionPane.showMessageDialog(this, "Data Updated Successfully");
        } catch (Exception e) {
            System.out.println("Error in ResultUpdate function"+e);
        }
        
    }//GEN-LAST:event_UpdateActionPerformed

    private void RnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RnameActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        viewResult vr = new viewResult();
        vr.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void RFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RFnameActionPerformed

    private void RidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RidActionPerformed

    private void Subject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subject1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Subject1ActionPerformed

    private void Subject2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subject2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Subject2ActionPerformed

    private void Subject3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subject3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Subject3ActionPerformed

    private void Subject4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subject4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Subject4ActionPerformed

    private void Subject5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subject5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Subject5ActionPerformed

    private void ClassBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassBoxActionPerformed

    private void SelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectActionPerformed
        // TODO add your handling code here:
        Sacred s = new Sacred();
     
        ResultSet rs = s.getResultById((Rid.getText()));
        
        try {
            
            if(rs.next() == false){
            JOptionPane.showMessageDialog(this, "Record not found");
            Rid.setText("");
            }
            else{
            //SID.setText(rs.getString("ID"));
            Rname.setText(rs.getString("Name"));
            RFname.setText(rs.getString("F_Name"));
            ClassBox.setText(rs.getString("Class"));
            Subject1.setText(rs.getString("Subject1"));
            Subject2.setText(rs.getString("Subject2"));
            Subject3.setText(rs.getString("Subject3"));
            Subject4.setText(rs.getString("Subject4"));
            Subject5.setText(rs.getString("Subject5"));

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_SelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField ClassBox;
    private javax.swing.JButton Delet;
    private javax.swing.JTextField RFname;
    private javax.swing.JTextField Rid;
    private javax.swing.JTextField Rname;
    private javax.swing.JButton Select;
    private javax.swing.JTextField Subject1;
    private javax.swing.JTextField Subject2;
    private javax.swing.JTextField Subject3;
    private javax.swing.JTextField Subject4;
    private javax.swing.JTextField Subject5;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
