/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.sql.ResultSet;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Haris Khan
 */
public class schoolLogin extends javax.swing.JFrame {

    /**
     * Creates new form schoolLogin
     */
    public schoolLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bluebackground = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        whiteBackground = new javax.swing.JPanel();
        passS = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        userS = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        backBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setPreferredSize(new java.awt.Dimension(1550, 900));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bluebackground.setBackground(new java.awt.Color(51, 102, 255));
        bluebackground.setMaximumSize(new java.awt.Dimension(1920, 1080));
        bluebackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 48)); // NOI18N
        jLabel1.setForeground(java.awt.Color.orange);
        jLabel1.setText("Developers");
        bluebackground.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 294, 64));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 48)); // NOI18N
        jLabel2.setForeground(java.awt.Color.orange);
        jLabel2.setText("Unique");
        bluebackground.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 294, 64));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/building.png"))); // NOI18N
        bluebackground.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 390, 660));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("_______________________________");
        bluebackground.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 320, -1));

        getContentPane().add(bluebackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 530, 1070));

        whiteBackground.setBackground(new java.awt.Color(255, 255, 255));
        whiteBackground.setMaximumSize(new java.awt.Dimension(1920, 1080));
        whiteBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passS.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        passS.setText("PASSWORD");
        whiteBackground.add(passS, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 421, 201, 52));

        user.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        whiteBackground.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 327, 550, 52));

        userS.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        userS.setText("USER ID");
        whiteBackground.add(userS, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 319, 201, 52));

        pass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        whiteBackground.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 424, 549, 52));

        backBtn.setBackground(java.awt.Color.gray);
        backBtn.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        whiteBackground.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 580, 253, 55));

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(152, 66, 225));
        jLabel3.setText("Login to Admin Dashboard");
        whiteBackground.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 144, 590, 45));

        jLabel4.setText("______________________________________________________________________________________");
        whiteBackground.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 190, 810, -1));

        login.setBackground(new java.awt.Color(54, 54, 237));
        login.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        whiteBackground.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 578, 253, 55));

        getContentPane().add(whiteBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 0, 1600, 1090));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        LandingPage landingPage = new LandingPage();
        landingPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed
    
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
          if (user.getText().equals("") || pass.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Username and Password");            
        } else {
        Sacred s = new Sacred();
        ResultSet rs = s.getuser(user.getText(),pass.getText());
        try{
            
            if (rs.next()) {
                dashBoard w = new dashBoard();
                w.setVisible(true);
                dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "Invalid Username or Password");
            }
        }
            catch(Exception e){
                    System.out.println(e);
                    }
          }
    }//GEN-LAST:event_loginActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(schoolLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(schoolLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(schoolLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(schoolLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new schoolLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel bluebackground;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel passS;
    private javax.swing.JTextField user;
    private javax.swing.JLabel userS;
    private javax.swing.JPanel whiteBackground;
    // End of variables declaration//GEN-END:variables
}
