/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HAMAZ KHAN
 */
public class viewResult extends javax.swing.JFrame {

    /**
     * Creates new form page5
     */
    
    public viewResult() {
        initComponents();
       
        ResultSet rs; 
       
      Sacred db=new Sacred();
      rs=db.displayResult();
      DefaultTableModel tb=(DefaultTableModel)jTable1.getModel();
      
      try{
      while(rs.next()){
        
        String subject1 = rs.getString("Subject1");
        String subject2 = rs.getString("Subject2").toString();
        String subject3 = rs.getString("Subject3").toString();
        String subject4 = rs.getString("Subject4").toString();
        String subject5 = rs.getString("Subject5").toString();

        float Total1 = Float.valueOf(subject1)+Float.valueOf(subject2)+Float.valueOf(subject3)+Float.valueOf(subject4)+Float.valueOf(subject5);
        String Total = Float.toString(Total1);
        
        String Grade = "";
          if (Total1 >= 400) {
              Grade = "A+";
          }
          else if(Total1 >= 350){
               Grade = "A";
          }     
          else if(Total1 >= 300){
               Grade = "B";
          }     
          else if(Total1 >= 250){
               Grade = "C";
          }
          else if(Total1 >= 200){
               Grade = "D";
          }
          else if(Total1 >= 199){
               Grade = "E";
          
          } else {
              Grade = "F";
          }
          
          String []data={rs.getString("SNO"), rs.getString("ID"),rs.getString("Name"),rs.getString("F_Name"),rs.getString("Class"),rs.getString("Subject1"),rs.getString("Subject2"),rs.getString("Subject3"),rs.getString("Subject4"),rs.getString("subject5"),Total,Grade};
        tb.addRow(data);
      }
      }catch(Exception e){
      
          JOptionPane.showMessageDialog(this, "Error"+e);
      }
    }
    
    class classSearch{
    public  void seraching(String str){
    DefaultTableModel tb = (DefaultTableModel)jTable1.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(tb);
        jTable1.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        school1 = new school.School();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        delet = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        Label_Print = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setPreferredSize(new java.awt.Dimension(1550, 900));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 182, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(1550, 120));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel1.setText("VIEW RESULT");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 370, 60));

        jLabel2.setText("________________________________________________________");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 440, 20));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 160));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 126, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(127, 218, 255));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SNO", "I.D", "Name", "F/Name", "Class", "Subject 1", "Subjec 2", "Subject 3", "Subject 4", "Subject 5", "Total", "Grade"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 1500, 530));

        jButton1.setBackground(new java.awt.Color(44, 165, 182));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 70, 140, 50));

        delet.setBackground(new java.awt.Color(51, 51, 51));
        delet.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        delet.setForeground(new java.awt.Color(51, 51, 51));
        delet.setText("Modify");
        delet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletActionPerformed(evt);
            }
        });
        jPanel1.add(delet, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 70, 130, 50));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/icons8-search-client-40.png"))); // NOI18N
        jLabel3.setText("Search");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 130, 50));

        searchBar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBarKeyReleased(evt);
            }
        });
        jPanel1.add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 200, 40));

        Label_Print.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Label_Print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/icons8-print-48.png"))); // NOI18N
        Label_Print.setText("Print");
        Label_Print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_PrintMouseClicked(evt);
            }
        });
        jPanel1.add(Label_Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 130, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1550, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         dashBoard db = new dashBoard();
        db.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletActionPerformed
        // TODO add your handling code here:
        resultSearch rs = new resultSearch();
        rs.setVisible(true);
        dispose();
    }//GEN-LAST:event_deletActionPerformed

    private void searchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyReleased
        // TODO add your handling code here:
        String seachvalue = searchBar.getText();
        classSearch cs = new classSearch();
        cs.seraching(seachvalue);
    }//GEN-LAST:event_searchBarKeyReleased

    private void Label_PrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_PrintMouseClicked
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Student Result");
        MessageFormat footer = new MessageFormat("H.K.A School");
        try {
            jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e) {
            JOptionPane.showInputDialog(null, "Cannot be Print", e.getMessage());
        }

    }//GEN-LAST:event_Label_PrintMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Print;
    private javax.swing.JButton delet;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private school.School school1;
    private javax.swing.JTextField searchBar;
    // End of variables declaration//GEN-END:variables
}
